Explicitly define ctype.h
Compiler is not happy when tolower() is called without definition.

cc -c -m32\
-DINCPATH="/tmp/inferno/module"\
-g -O -fno-strict-aliasing -fno-aggressive-loop-optimizations\
-Wuninitialized -Wunused-variable -Wreturn-type -Wimplicit\
-I/tmp/inferno/Linux/386/include\
-I/tmp/inferno/include\
-DLINUX_386 -o y.tab.o y.tab.c

limbo.y: In function ‘win2inf’:
limbo.y:1938:30: error: implicit declaration of function ‘tolower’
[-Wimplicit-function-declaration]
 1938 |                         *t = tolower(*t);
      |                              ^~~~~~~
limbo.y:3:1: note: include ‘<ctype.h>’ or provide a declaration of
‘tolower’
    2 | #include "limbo.h"
  +++ |+#include <ctype.h>
    3 | %}