Added explicit declation of nrand()
Compiler not happy about nrand() being implicitly declared

cc -c -m32 -DROOT="/tmp/inferno" -DEMU\
-I. -I../port\
-I/tmp/inferno/Linux/386/include\
-I/tmp/inferno/include\
-I/tmp/inferno/libinterp\
-g -O -fno-strict-aliasing -fno-aggressive-loop-optimizations\
-Wuninitialized -Wunused-variable -Wreturn-type -Wimplicit\
-I/tmp/inferno/Linux/386/include\
-I/tmp/inferno/include\
-D_GNU_SOURCE\
-DLINUX_386\
-I. ../port/devssl.c

../port/devssl.c: In function ‘randfill’:
../port/devssl.c:619:26: error: implicit declaration of function
‘nrand’; did you mean ‘srand’? [-Wimplicit-function-declaration]
  619 |                 *buf++ = nrand(256);
      |                          ^~~~~
      |                          srand